return {
  "pwntester/octo.nvim",
  dependencies = {
    "nvim-lua/plenary.nvim",
    -- "nvim-telescope/telescope.nvim",
    "ibhagwan/fzf-lua",
    "nvim-tree/nvim-web-devicons",
    "sindrets/diffview.nvim",
  },
  cmd = "Octo",
  opts = {
    use_local_fs = false,
    enable_builtin = true,
    default_to_projects_v2 = true,
    default_remote = { "upstream", "origin" },
    ssh_aliases = {},
    picker = "fzf-lua",
    -- picker = "telescope",
    picker_config = {
      use_emojis = true,
    },
    comment_icon = "▎",
    outdated_icon = "󰅒 ",
    resolved_icon = " ",
    reaction_viewer_hint_icon = " ",
    user_icon = " ",
    timeline_marker = " ",
    timeline_indent = 2,
    right_bubble_delimiter = "",
    left_bubble_delimiter = "",
    github_hostname = "",
    snippet_context_lines = 4,
    gh_env = {},
    timeout = 5000,
    default_merge_method = "merge",
    colors = {
      white = "#ffffff",
      grey = "#2A354C",
      black = "#000000",
      red = "#db4b4b",
      dark_red = "#f7768e",
      green = "#9ece6a",
      dark_green = "#41a6b5",
      yellow = "#e0af68",
      dark_yellow = "#ff9e64",
      cyan = "#449dab",
      magenta = "#bb9af7",
      blue = "#4e76ac",
      dark_blue = "#73daca",
      orange = "#ff9e64",
    },
    ui = {
      use_signcolumn = true,
    },
    issues = {
      order_by = {
        field = "CREATED_AT",
        direction = "DESC",
      },
    },
    pull_requests = {
      order_by = {
        field = "CREATED_AT",
        direction = "DESC",
      },
      always_select_remote_on_create = false,
    },
    file_panel = {
      size = 10,
      icons = true,
    },
    mappings = {
      issue = {
        close_issue = { lhs = "<leader>oic", desc = "close issue" },
        reopen_issue = { lhs = "<leader>oio", desc = "reopen issue" },
        list_issues = { lhs = "<leader>oil", desc = "list open issues on same repo" },
        reload = { lhs = "<C-r>", desc = "reload issue" },
        open_in_browser = { lhs = "<C-b>", desc = "open issue in browser" },
        copy_url = { lhs = "<C-y>", desc = "copy url to system clipboard" },
        add_assignee = { lhs = "<leader>oaa", desc = "add assignee" },
        remove_assignee = { lhs = "<leader>oad", desc = "remove assignee" },
        create_label = { lhs = "<leader>olc", desc = "create label" },
        add_label = { lhs = "<leader>ola", desc = "add label" },
        remove_label = { lhs = "<leader>old", desc = "remove label" },
        goto_issue = { lhs = "<leader>ogi", desc = "navigate to a local repo issue" },
        add_comment = { lhs = "<leader>oca", desc = "add comment" },
        delete_comment = { lhs = "<leader>ocd", desc = "delete comment" },
        next_comment = { lhs = "]c", desc = "go to next comment" },
        prev_comment = { lhs = "[c", desc = "go to previous comment" },
        react_hooray = { lhs = "<leader>orp", desc = "add/remove 🎉 reaction" },
        react_heart = { lhs = "<leader>orh", desc = "add/remove ❤️ reaction" },
        react_eyes = { lhs = "<leader>ore", desc = "add/remove 👀 reaction" },
        react_thumbs_up = { lhs = "<leader>or+", desc = "add/remove 👍 reaction" },
        react_thumbs_down = { lhs = "<leader>or-", desc = "add/remove 👎 reaction" },
        react_rocket = { lhs = "<leader>orr", desc = "add/remove 🚀 reaction" },
        react_laugh = { lhs = "<leader>orl", desc = "add/remove 😄 reaction" },
        react_confused = { lhs = "<leader>orc", desc = "add/remove 😕 reaction" },
      },
      pull_request = {
        checkout_pr = { lhs = "<leader>opo", desc = "checkout PR" },
        merge_pr = { lhs = "<leader>opm", desc = "merge PR" },
        squash_and_merge_pr = { lhs = "<leader>opsm", desc = "squash and merge PR" },
        rebase_and_merge_pr = { lhs = "<leader>oprm", desc = "rebase and merge PR" },
        list_commits = { lhs = "<leader>opc", desc = "list PR commits" },
        list_changed_files = { lhs = "<leader>opf", desc = "list PR changed files" },
        show_pr_diff = { lhs = "<leader>opd", desc = "show PR diff" },
        add_reviewer = { lhs = "<leader>ova", desc = "add reviewer" },
        remove_reviewer = { lhs = "<leader>ovd", desc = "remove reviewer" },
        close_issue = { lhs = "<leader>oic", desc = "close PR" },
        reopen_issue = { lhs = "<leader>oio", desc = "reopen PR" },
        list_issues = { lhs = "<leader>oil", desc = "list open issues on same repo" },
        reload = { lhs = "<C-r>", desc = "reload PR" },
        open_in_browser = { lhs = "<C-b>", desc = "open PR in browser" },
        copy_url = { lhs = "<C-y>", desc = "copy url to system clipboard" },
        goto_file = { lhs = "gf", desc = "go to file" },
        add_assignee = { lhs = "<leader>oaa", desc = "add assignee" },
        remove_assignee = { lhs = "<leader>oad", desc = "remove assignee" },
        create_label = { lhs = "<leader>olc", desc = "create label" },
        add_label = { lhs = "<leader>ola", desc = "add label" },
        remove_label = { lhs = "<leader>old", desc = "remove label" },
        goto_issue = { lhs = "<leader>ogi", desc = "navigate to a local repo issue" },
        add_comment = { lhs = "<leader>oca", desc = "add comment" },
        delete_comment = { lhs = "<leader>ocd", desc = "delete comment" },
        next_comment = { lhs = "]c", desc = "go to next comment" },
        prev_comment = { lhs = "[c", desc = "go to previous comment" },
        react_hooray = { lhs = "<leader>orp", desc = "add/remove 🎉 reaction" },
        react_heart = { lhs = "<leader>orh", desc = "add/remove ❤️ reaction" },
        react_eyes = { lhs = "<leader>ore", desc = "add/remove 👀 reaction" },
        react_thumbs_up = { lhs = "<leader>or+", desc = "add/remove 👍 reaction" },
        react_thumbs_down = { lhs = "<leader>or-", desc = "add/remove 👎 reaction" },
        react_rocket = { lhs = "<leader>orr", desc = "add/remove 🚀 reaction" },
        react_laugh = { lhs = "<leader>orl", desc = "add/remove 😄 reaction" },
        react_confused = { lhs = "<leader>orc", desc = "add/remove 😕 reaction" },
      },
      review_thread = {
        goto_issue = { lhs = "<leader>ogi", desc = "navigate to a local repo issue" },
        add_comment = { lhs = "<leader>oca", desc = "add comment" },
        add_suggestion = { lhs = "<leader>osa", desc = "add suggestion" },
        delete_comment = { lhs = "<leader>ocd", desc = "delete comment" },
        next_comment = { lhs = "]c", desc = "go to next comment" },
        prev_comment = { lhs = "[c", desc = "go to previous comment" },
        select_next_entry = { lhs = "]q", desc = "move to next changed file" },
        select_prev_entry = { lhs = "[q", desc = "move to previous changed file" },
        select_first_entry = { lhs = "[Q", desc = "move to first changed file" },
        select_last_entry = { lhs = "]Q", desc = "move to last changed file" },
        close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
        react_hooray = { lhs = "<leader>orp", desc = "add/remove 🎉 reaction" },
        react_heart = { lhs = "<leader>orh", desc = "add/remove ❤️ reaction" },
        react_eyes = { lhs = "<leader>ore", desc = "add/remove 👀 reaction" },
        react_thumbs_up = { lhs = "<leader>or+", desc = "add/remove 👍 reaction" },
        react_thumbs_down = { lhs = "<leader>or-", desc = "add/remove 👎 reaction" },
        react_rocket = { lhs = "<leader>orr", desc = "add/remove 🚀 reaction" },
        react_laugh = { lhs = "<leader>orl", desc = "add/remove 😄 reaction" },
        react_confused = { lhs = "<leader>orc", desc = "add/remove 😕 reaction" },
      },
      submit_win = {
        approve_review = { lhs = "<C-a>", desc = "approve review" },
        comment_review = { lhs = "<C-m>", desc = "comment review" },
        request_changes = { lhs = "<C-r>", desc = "request changes review" },
        close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
      },
      review_diff = {
        add_review_comment = { lhs = "<leader>oca", desc = "add a new review comment" },
        add_review_suggestion = { lhs = "<leader>osa", desc = "add a new review suggestion" },
        focus_files = { lhs = "<leader>e", desc = "move focus to changed file panel" },
        toggle_files = { lhs = "<leader>b", desc = "hide/show changed files panel" },
        next_thread = { lhs = "]t", desc = "move to next thread" },
        prev_thread = { lhs = "[t", desc = "move to previous thread" },
        select_next_entry = { lhs = "]q", desc = "move to next changed file" },
        select_prev_entry = { lhs = "[q", desc = "move to previous changed file" },
        select_first_entry = { lhs = "[Q", desc = "move to first changed file" },
        select_last_entry = { lhs = "]Q", desc = "move to last changed file" },
        close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
        toggle_viewed = { lhs = "<leader><leader>o", desc = "toggle viewer viewed state" },
        goto_file = { lhs = "gf", desc = "go to file" },
      },
      file_panel = {
        next_entry = { lhs = "j", desc = "move to next changed file" },
        prev_entry = { lhs = "k", desc = "move to previous changed file" },
        select_entry = { lhs = "<cr>", desc = "show selected changed file diffs" },
        refresh_files = { lhs = "R", desc = "refresh changed files panel" },
        focus_files = { lhs = "<leader>e", desc = "move focus to changed file panel" },
        toggle_files = { lhs = "<leader>b", desc = "hide/show changed files panel" },
        select_next_entry = { lhs = "]q", desc = "move to next changed file" },
        select_prev_entry = { lhs = "[q", desc = "move to previous changed file" },
        select_first_entry = { lhs = "[Q", desc = "move to first changed file" },
        select_last_entry = { lhs = "]Q", desc = "move to last changed file" },
        close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
        toggle_viewed = { lhs = "<leader><leader>o", desc = "toggle viewer viewed state" },
      },
    },
  },
}
