return {
  "pwntester/octo.nvim",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "ibhagwan/fzf-lua",
    "nvim-tree/nvim-web-devicons",
    "sindrets/diffview.nvim",
  },
  cmd = "Octo",
  opts = {
    use_local_fs = false,
    enable_builtin = true,
    default_to_projects_v2 = true,
    default_remote = { "upstream", "origin" },
    picker = "fzf-lua",
    picker_config = {
      use_emojis = true,
    },
    snippet_context_lines = 4,
    timeout = 5000,
    default_merge_method = "merge",
    ui = {
      use_signcolumn = true, -- default is false
    },
    file_panel = {
      size = 10,
      icons = true,
    },
    -- tokyonight-flavoured palette (overrides octo's GitHub-coloured defaults)
    colors = {
      white = "#ffffff",
      grey = "#2A354C",
      black = "#000000",
      red = "#db4b4b",
      dark_red = "#f7768e",
      green = "#9ece6a",
      dark_green = "#41a6b5",
      yellow = "#e0af68",
      dark_yellow = "#ff9e64",
      cyan = "#449dab",
      magenta = "#bb9af7",
      blue = "#4e76ac",
      dark_blue = "#73daca",
      orange = "#ff9e64",
    },
    -- Only the bindings below differ from octo's defaults: octo defaults live
    -- under <localleader>, we relocate them into a <leader>o namespace. Anything
    -- matching the default (<C-*>, bracket motions, gf, j/k, etc.) is left to
    -- octo and intentionally omitted here. octo deep-merges, so defaults remain.
    mappings = {
      issue = {
        close_issue = { lhs = "<leader>oic", desc = "close issue" },
        reopen_issue = { lhs = "<leader>oio", desc = "reopen issue" },
        list_issues = { lhs = "<leader>oil", desc = "list open issues on same repo" },
        add_assignee = { lhs = "<leader>oaa", desc = "add assignee" },
        remove_assignee = { lhs = "<leader>oad", desc = "remove assignee" },
        create_label = { lhs = "<leader>olc", desc = "create label" },
        add_label = { lhs = "<leader>ola", desc = "add label" },
        remove_label = { lhs = "<leader>old", desc = "remove label" },
        goto_issue = { lhs = "<leader>ogi", desc = "navigate to a local repo issue" },
        add_comment = { lhs = "<leader>oca", desc = "add comment" },
        delete_comment = { lhs = "<leader>ocd", desc = "delete comment" },
        react_hooray = { lhs = "<leader>orp", desc = "add/remove 🎉 reaction" },
        react_heart = { lhs = "<leader>orh", desc = "add/remove ❤️ reaction" },
        react_eyes = { lhs = "<leader>ore", desc = "add/remove 👀 reaction" },
        react_thumbs_up = { lhs = "<leader>or+", desc = "add/remove 👍 reaction" },
        react_thumbs_down = { lhs = "<leader>or-", desc = "add/remove 👎 reaction" },
        react_rocket = { lhs = "<leader>orr", desc = "add/remove 🚀 reaction" },
        react_laugh = { lhs = "<leader>orl", desc = "add/remove 😄 reaction" },
        react_confused = { lhs = "<leader>orc", desc = "add/remove 😕 reaction" },
      },
      pull_request = {
        checkout_pr = { lhs = "<leader>opo", desc = "checkout PR" },
        merge_pr = { lhs = "<leader>opm", desc = "merge PR" },
        squash_and_merge_pr = { lhs = "<leader>opsm", desc = "squash and merge PR" },
        rebase_and_merge_pr = { lhs = "<leader>oprm", desc = "rebase and merge PR" },
        list_commits = { lhs = "<leader>opc", desc = "list PR commits" },
        list_changed_files = { lhs = "<leader>opf", desc = "list PR changed files" },
        show_pr_diff = { lhs = "<leader>opd", desc = "show PR diff" },
        add_reviewer = { lhs = "<leader>ova", desc = "add reviewer" },
        remove_reviewer = { lhs = "<leader>ovd", desc = "remove reviewer" },
        close_issue = { lhs = "<leader>oic", desc = "close PR" },
        reopen_issue = { lhs = "<leader>oio", desc = "reopen PR" },
        list_issues = { lhs = "<leader>oil", desc = "list open issues on same repo" },
        add_assignee = { lhs = "<leader>oaa", desc = "add assignee" },
        remove_assignee = { lhs = "<leader>oad", desc = "remove assignee" },
        create_label = { lhs = "<leader>olc", desc = "create label" },
        add_label = { lhs = "<leader>ola", desc = "add label" },
        remove_label = { lhs = "<leader>old", desc = "remove label" },
        goto_issue = { lhs = "<leader>ogi", desc = "navigate to a local repo issue" },
        add_comment = { lhs = "<leader>oca", desc = "add comment" },
        delete_comment = { lhs = "<leader>ocd", desc = "delete comment" },
        react_hooray = { lhs = "<leader>orp", desc = "add/remove 🎉 reaction" },
        react_heart = { lhs = "<leader>orh", desc = "add/remove ❤️ reaction" },
        react_eyes = { lhs = "<leader>ore", desc = "add/remove 👀 reaction" },
        react_thumbs_up = { lhs = "<leader>or+", desc = "add/remove 👍 reaction" },
        react_thumbs_down = { lhs = "<leader>or-", desc = "add/remove 👎 reaction" },
        react_rocket = { lhs = "<leader>orr", desc = "add/remove 🚀 reaction" },
        react_laugh = { lhs = "<leader>orl", desc = "add/remove 😄 reaction" },
        react_confused = { lhs = "<leader>orc", desc = "add/remove 😕 reaction" },
      },
      review_thread = {
        goto_issue = { lhs = "<leader>ogi", desc = "navigate to a local repo issue" },
        add_comment = { lhs = "<leader>oca", desc = "add comment" },
        add_suggestion = { lhs = "<leader>osa", desc = "add suggestion" },
        delete_comment = { lhs = "<leader>ocd", desc = "delete comment" },
        react_hooray = { lhs = "<leader>orp", desc = "add/remove 🎉 reaction" },
        react_heart = { lhs = "<leader>orh", desc = "add/remove ❤️ reaction" },
        react_eyes = { lhs = "<leader>ore", desc = "add/remove 👀 reaction" },
        react_thumbs_up = { lhs = "<leader>or+", desc = "add/remove 👍 reaction" },
        react_thumbs_down = { lhs = "<leader>or-", desc = "add/remove 👎 reaction" },
        react_rocket = { lhs = "<leader>orr", desc = "add/remove 🚀 reaction" },
        react_laugh = { lhs = "<leader>orl", desc = "add/remove 😄 reaction" },
        react_confused = { lhs = "<leader>orc", desc = "add/remove 😕 reaction" },
      },
      review_diff = {
        add_review_comment = { lhs = "<leader>oca", desc = "add a new review comment" },
        add_review_suggestion = { lhs = "<leader>osa", desc = "add a new review suggestion" },
        focus_files = { lhs = "<leader>e", desc = "move focus to changed file panel" },
        toggle_files = { lhs = "<leader>b", desc = "hide/show changed files panel" },
        toggle_viewed = { lhs = "<leader><leader>o", desc = "toggle viewer viewed state" },
      },
      file_panel = {
        focus_files = { lhs = "<leader>e", desc = "move focus to changed file panel" },
        toggle_files = { lhs = "<leader>b", desc = "hide/show changed files panel" },
        toggle_viewed = { lhs = "<leader><leader>o", desc = "toggle viewer viewed state" },
      },
    },
  },
}
